# Generated by Django 5.0.1 on 2024-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_time', models.DurationField()),
                ('date_create', models.DateField()),
                ('date_finish', models.DateField()),
            ],
        ),
    ]
