# Generated by Django 5.0.1 on 2024-02-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('issuer_number', models.CharField(max_length=20)),
                ('station_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('related_services', models.TextField()),
                ('additional_services', models.TextField()),
                ('ai_92', models.BooleanField()),
                ('ai_95', models.BooleanField()),
                ('dt', models.BooleanField()),
                ('dt_arctic', models.BooleanField()),
                ('ai_92_taneko', models.BooleanField()),
                ('ai_98_taneko', models.BooleanField()),
                ('dt_taneko', models.BooleanField()),
                ('sug', models.BooleanField()),
                ('electric_charging', models.BooleanField()),
                ('ai_98', models.BooleanField()),
                ('ai_95_taneko', models.BooleanField()),
                ('adblue', models.BooleanField()),
                ('ai_100', models.BooleanField()),
                ('ai_80', models.BooleanField()),
                ('dt_winter', models.BooleanField()),
                ('kpg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstations.gasstation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
    ]
